services:
  api:
    build: api/
    ports:
      - 3000:3000
  # events:
  #   build: events/
  #   network_mode: host
  #   depends_on:
  #     - api
  #   # command: node ./index.js
  #   ports:
  #     - 80:80
