services:
  api:
    container_name: kaboodle_api
    build: api/
    ports:
      - 3001:3001
    volumes:
      - data:/api/data
  events:
    container_name: kaboodle_events
    build: events/
    ports:
      - 3000:3000

volumes:
  data:
    name: kaboodle_data
