version: 2
services:
  api:
    build: 
      context: ./api/
      dockerfile: Dockerfile
    ports: 
      - "3000:80"
  events:
    build:
      context: ./events/
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
