services:
  database:
    container_name: kaboodle_db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kaboodle
  api:
    container_name: kaboodle_api
    build: api/
    ports:
      - 3000:3000
    depends_on:
      - database

  # events:
  #   build: events/
  #   network_mode: host
  #   depends_on:
  #     - api
  #   # command: node ./index.js
  #   ports:
  #     - 80:80
# volumes:
#   data:
#     external: true

# networks:
# database:
#   driver: bridge
